epark/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path
from . import views
from parking.views import ParkingListView
from django.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/login", views.login_view, name="login"),
    path("user/logout", views.logout_view, name="logout"),
    path("user/register", views.register_view, name="register"),
    path("parking/parkings", ParkingListView.as_view(), name="parking"),
    path("", views.index, name='index'),
    path("parking/", include('parking.urls')),
    path("reserves/", include('reserves.urls')),
    path('order/', include('orders.urls')),
    path("owner/register", views.register_owner_view, name="register_owner"),
    path("owner/login", views.login_owner_view, name="login_owner"),
    path("contact", views.contact_view, name="contact"),
    #path("owner/logout", views.logout_owner_view, name="logout_owner"),
    
]

urlpatterns += staticfiles_urlpatterns()

parking/urls.py
from django.urls import path
from . import views

app_name = 'parking'
urlpatterns = [
    path('search', views.ParkingSearchListView.as_view(), name='search'),
    path('<slug:slug>', views.ParkingDetailView.as_view(), name='parking'),

]

parking/models.py
from pyexpat import model
from django.db import models
from django.utils.text import slugify
import uuid
from django.db.models.signals import pre_save

# Create your models here.
class Parking(models.Model):
    # crea tabla en la base de datos, los atributos son las columnas de las tablas.
    title = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    owner_name = models.CharField(max_length=50)
    owner_surname = models.CharField(max_length=50)
    address_p  = models.TextField()   
    # x_address # cordenadas para la imprementacion de la API de map
    # y_address
    price_hour = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)        
    price_day = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)        
    price_week = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)        
    price_month = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    phone_p = models.CharField(max_length=20)
    mail_p = models.EmailField()
    country_p = models.CharField(max_length=30)
    city_p = models.CharField(max_length=30)
    slots =  models.IntegerField()    
    url_map = models.CharField(max_length=500)
    avalaible = models.BooleanField(default=True)
    slug = models.SlugField(null=False, blank=False, unique=True) 
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.CharField(max_length=500)
    
    def __str__(self) -> str:
        return self.title

class Users(models.Model):
    user_name = models.CharField(max_length=50)
    user_surname = models.CharField(max_length=50)
    phone_u = models.CharField(max_length=20)
    mail_u = models.EmailField()
    country_u = models.CharField(max_length=30)
    city_u = models.CharField(max_length=30)
    car_plate = models.CharField(max_length=20, default="sin confirmar")
    # card = models.CharField(max_length=20)

class Reservations(models.Model):
    user_name = models.ForeignKey(Parking, on_delete=models.CASCADE)
    title = models.ForeignKey(Users, on_delete=models.CASCADE)

    """
        MODIFICADO POR SIGNALS
    def save(self, *args, **kwargs):
        # Guarda el slug
        self.slug = slugify(self.title)
        super(Parking, self).save(*args, **kwargs)"""

    def __str__(self) -> str:
        return self.title

def set_slug(sender, instance, *args, **kwargs): # Debe recibir 5 elementos
    if instance.title and not instance.slug:
        slug = slugify(instance.title)

        
        # si existe algun objeto con ese slug, genera uno nuevo
        while Parking.objects.filter(slug=slug).exists():
            # pone caracteres aleatorios con la libreria uuid
            slug = slugify(
                '{}-{}'.format(instance.title, str(uuid.uuid4())[:8]  )
            )
        # La instancia es nuestro objeto almacenado
        instance.slug = slug
    
# Antes de que un objeto parking se almacene se ejecutra el callback set_slug
pre_save.connect(set_slug, sender=Parking)

parking/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
# Create your views here.
from .models import Parking

class ParkingListView(ListView):
    template_name = 'parking/parkings.html'
    queryset = Parking.objects.all()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # toma los contextos
        context['parkings'] = context['object_list']
        return context

class ParkingDetailView(DetailView):
    # Obtiene un objeto o registro de nuestra base de datos
    # mediante un id unico
    # indicar con que modelo vamos a trabajar
    model = Parking
    template_name = 'parking/parking.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # toma los contextos
        
        return context


class ParkingSearchListView(ListView):
    template_name = 'parking/search.html'    

    def get_queryset(self):
        return Parking.objects.filter(title__icontains=self.query())

    def query(self):
        return self.request.GET.get('q')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # toma los contextos
        context['query'] = self.query()        
        context['count'] = context['object_list'].count()
        return context

parking/templates/parking/snippets/list.html
{% for parking in parkings %}
    <div class="col3 mt-5">
        {% include 'parking/snippets/parking.html' %}
    </div>
{% endfor %}

parking/templates/parking/snippets/parking.html
<div class="mb-4">
                    <div class="package-item bg-white mb-2">
                        <img class="img-fluid" src="..\..\..\..\static\image\parking-banner.jpg" alt="">
                        <div class="p-3">
                            <div class="d-flex justify-content-between mb-3">
                                <h6 class="m-0"><i class="fa fa-map-marker-alt text-primary mr-2"></i> {{ parking.address_p }}</h6>                                
                                <h6 class="m-0"><i class="fa fa-star text-primary mr-2"></i>4.5 <h6>({{ parking.slots }})</h6>                                
                                <h6 class="m-0"><i class="fa fa-car text-primary mr-2"></i> {{ parking.slots }}</h6>
                            </div>
                            <div class="col h5 text-decoration-none">
                                {{ parking.title }}
                            </div>
                            <div class="row">
                                <div class="col  align-self-center">                                    
                                        <a class="h5 text-decoration-none" href="{% url 'parking:parking' parking.slug %}"><button  class="btn btn-primary">Seleccionar</button></a>                                                                            
                                </div>
                                <div class="col align-self-center">                                    
                                    <h6 class="text-primary"><i class="text-dark">Hora:</i> ${{ parking.price_hour }}</h6>
                                </div>                                
                            </div>
                        </div>
                    </div>
                </div>

parking/templates/parking/snippets/search.html
<form action="{% url 'parking:search' %} ">
    <div class="container-fluid booking mt-3">
        <div class="container pb-3">
            <div class="bg-light shadow p-4">
                <div class="row align-items-center" style="min-height: 60px;">
                    <div class="col-md-10">
                        <div class="row">                        
                            <div class="">
                                <div class="mb-3 mb-md-0">
                                    <div class="date" id="date1" data-target-input="nearest">
                                        <input type="text" class="form-control datetimepicker-input p-3" name="q" placeholder="Buscar" value="{{ query }}">                                    
                                    </div>
                                </div>
                            </div>                        
                        </div>
                    </div>
                    <div class="col-md-2">
                        <input type="submit" value="Buscar" class="btn btn-primary btn-block p-3">                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>