epark/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path
from . import views
from parking.views import ParkingListView
from django.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/login", views.login_view, name="login"),
    path("user/logout", views.logout_view, name="logout"),
    path("user/register", views.register_view, name="register"),
    path("parking/parkings", ParkingListView.as_view(), name="parking"),
    path("", views.index, name='index'),
    path("parking/", include('parking.urls')),
    path("reserves/", include('reserves.urls')),
    path('order/', include('orders.urls')),
    path("owner/register", views.register_owner_view, name="register_owner"),
    path("owner/login", views.login_owner_view, name="login_owner"),
    path("contact", views.contact_view, name="contact"),
    #path("owner/logout", views.logout_owner_view, name="logout_owner"),
    
]

urlpatterns += staticfiles_urlpatterns()

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'
urlpatterns = [
    path('', views.order, name='order'),
    path('credit-card', views.credit_card, name='credit-card'),
    path('confirm', views.confirm, name='confirm')
    
]

orders/models.py
from django.db import models
from users.models import User
from reserves.models import Reserve
from enum import Enum
from django.db.models.signals import pre_save
import uuid
# Create your models here.

class OrderStatus(Enum):
    CREATED = 'CREATED'
    PAYED = 'PAYED'
    COMPLETED = 'COMPLETED'
    CANCELED = 'CANCELED'

choices = [ (tag, tag.value) for tag in OrderStatus ]

class Order(models.Model):
    order_id = models.CharField(max_length=100, null=False, blank=False, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reserve = models.ForeignKey(Reserve, on_delete=models.CASCADE)
    status = models.CharField(max_length=40, choices=choices, default=OrderStatus.CREATED) 
    total = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.order_id
    
    def update_total(self):
        self.total = self.get_total()
        self.save()
    
    def get_total(self):
        return self.reserve.total



def set_order_id(sender, instance, *args, **kwargs):
    if not instance.order_id:
        instance.order_id = str(uuid.uuid4())

def set_total(sender, instance, *args, **kwargs):
    instance.total = instance.get_total()

# Antes que se almacenen los objetos order, se ejecutan los callbacks
pre_save.connect(set_order_id, sender=Order)
pre_save.connect(set_total, sender=Order)

orders/views.py
from unicodedata import name
from django.shortcuts import render
from reserves.utils import get_or_create_reserve
from .models import Order
from .utils import get_or_create_order
from django.contrib.auth.decorators import login_required
from .utils import breadcrumb

# Create your views here.

@login_required(login_url='login')
def order(request):
    reserve = get_or_create_reserve(request)
    order = get_or_create_order(reserve, request)

    return render(request, 'orders/order.html', {
        'reserve':reserve,
        'order':order,
        'breadcrumb': breadcrumb()
        
    } )

@login_required(login_url='login')
def credit_card(request):
    return render(request, 'orders/credit_card.html')

@login_required(login_url='confirm')
def confirm(request):
    reserve = get_or_create_reserve(request)
    order = get_or_create_order(reserve, request)
    
    return render(request, 'orders/confirm.html', {
        'reserve':reserve,
        'order':order,
        'breadcrumb': breadcrumb()
        
    } )

orders/templates/orders/confirm.html
{% extends 'base.html' %}

{% block breadcrumb %}
    {% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}

{% block content%}
{% load parking_extras %}

    <div class="col-6 ms-5 p-5 mb-5">
        <div class="h3 ">
            Comprobante de Pago
        </div>
        <br>
        <div class="card">
            <div class="card-header bg-warning">
                <p class="h2">Ticket:</p>
                    <p class="p-2 h-2 fw-bold bg-dark text-light">Número de orden: 0004568782</p>
            </div> 
            <div class="card-body">
                    {% for parking in reserve.parkings.all %}
                        {% include 'orders/snippets/parking.html' %}
                    {% endfor%} 
            </div>  
            <div class="card text-bg-success ">                               
                    <p class="h4 ms-3 mt-3">Estado: Pago Concretado</p>
                    <p class="h4 ms-3">Total: <span class="h3 text-light fw-bold ms-3">{{ order.total | price_format }}</span></p>
                    
            </div>                        
    </div>
    
{% endblock%}

orders/templates/orders/credit_card.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
  <link href="https://fonts.googleapis.com/css?family=Lato|Liu+Jian+Mao+Cao&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="../../../static/css/credit_card.css">  
  
{% endblock %}

{% block content %}
  <div class="col">
    <!-- <div class="h3">
      Nuevo método de pago
    </div> -->
    <div class="contenedor">

      <!-- Tarjeta -->
      <section class="tarjeta" id="tarjeta">
        <div class="delantera">
          <div class="logo-marca" id="logo-marca">
            <!-- <img src="img/logos/visa.png" alt=""> -->
          </div>
          
          <div class="datos">
            <div class="grupo" id="numero">
              <p class="label">Número Tarjeta</p>
              <p class="numero">#### #### #### ####</p>
            </div>
            <div class="flexbox">
              <div class="grupo" id="nombre">
                <p class="label">Nombre Tarjeta</p>
                <p class="nombre"></p>
              </div>
  
              <div class="grupo" id="expiracion">
                <p class="label">Expiracion</p>
                <p class="expiracion"><span class="mes">MM</span> / <span class="year">AA</span></p>
              </div>
            </div>
          </div>
        </div>
  
        <div class="trasera">
          <div class="barra-magnetica"></div>
          <div class="datos">
            <div class="grupo" id="firma">
              <p class="label">Firma</p>
              <div class="firma"><p></p></div>
            </div>
            <div class="grupo" id="ccv">
              <p class="label">CCV</p>
              <p class="ccv"></p>
            </div>
          </div>
          <p class="leyenda">Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus exercitationem, voluptates illo.</p>
          <a href="#" class="link-banco">www.tubanco.com</a>
        </div>
      </section>
  
      <!-- Contenedor Boton Abrir Formulario -->
      <div class="contenedor-btn">
        <button class="btn-abrir-formulario" id="btn-abrir-formulario">
          <i class="fas fa-plus"></i>
        </button>
      </div>
  
      <!-- Formulario -->
      <form action="" id="formulario-tarjeta" class="formulario-tarjeta active">
        <div class="grupo">
          <label for="inputNumero">Número Tarjeta</label>
          <input type="text" id="inputNumero" maxlength="19" autocomplete="off">
        </div>
        <div class="grupo">
          <label for="inputNombre">Nombre</label>
          <input type="text" id="inputNombre" maxlength="19" autocomplete="off">
        </div>
        <div class="flexbox">
          <div class="grupo expira">
            <label for="selectMes">Expiracion</label>
            <div class="flexbox">
              <div class="grupo-select">
                <select name="mes" id="selectMes">
                  <option disabled selected>Mes</option>
                </select>
                <i class="fas fa-angle-down"></i>
              </div>
              <div class="grupo-select">
                <select name="year" id="selectYear">
                  <option disabled selected>Año</option>
                </select>
                <i class="fas fa-angle-down"></i>
              </div>
            </div>
          </div>
  
          <div class="grupo ccv">
            <label for="inputCCV">CCV</label>
            <input type="text" id="inputCCV" maxlength="3">
          </div>
        </div>
      </form>
      
        <div class="row" style="margin-top: -100px">
          <div class="col">
            <a href="{% url 'orders:confirm' %} "><button class="btn btn-success border rounded-pill p-3" style="width: 200px">Pagar</button></a>
          </div>
          <div class="col">
            <a href="{% url 'orders:order' %} "><button class="btn btn-danger border rounded-pill p-3" style="width: 200px">Cancelar</button></a>
          </div>
        </div>
      
    </div>  
  
  </div>
{% endblock %}

{% block javascript %}
  <script src="https://kit.fontawesome.com/2c36e9b7b1.js" crossorigin="anonymous"></script>
  <script src="{% static 'js/credit_card.js' %} "></script>  
{% endblock %}

orders/templates/orders/order.html
{% extends 'base.html' %}

{% block breadcrumb %}
    {% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}

{% block content%}
{% load parking_extras %}
<div class="p-5" style="height: 75vh">
    <div class="col-8">
        <div class="h3">
            Revisa tu reserva antes de realizar el Pago
        </div>
        <div class="card w-75">
            <div class="card-body">
                {% for parking in reserve.parkings.all %}
                    {% include 'orders/snippets/parking.html' %}
                {% endfor%}                
            </div>         
        </div>
        {% include 'orders/snippets/resume.html' %}
        
        </div>
    </div>
</div>
{% endblock%}