epark/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path
from . import views
from parking.views import ParkingListView
from django.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/login", views.login_view, name="login"),
    path("user/logout", views.logout_view, name="logout"),
    path("user/register", views.register_view, name="register"),
    path("parking/parkings", ParkingListView.as_view(), name="parking"),
    path("", views.index, name='index'),
    path("parking/", include('parking.urls')),
    path("reserves/", include('reserves.urls')),
    path('order/', include('orders.urls')),
    path("owner/register", views.register_owner_view, name="register_owner"),
    path("owner/login", views.login_owner_view, name="login_owner"),
    path("contact", views.contact_view, name="contact"),
    #path("owner/logout", views.logout_owner_view, name="logout_owner"),
    
]

urlpatterns += staticfiles_urlpatterns()

reserves/urls.py
from django.urls import path 
from . import views

app_name = 'reserves'
urlpatterns = [
    path('', views.reserve, name='reserve'),
    path('add', views.add, name='add'),
    path('remove', views.remove, name='remove'),
    
]

reserves/models.py
from django.db import models
from users.models import User
from parking.models import Parking
import uuid
from django.db.models.signals import pre_save
from django.db.models.signals import m2m_changed
from django.db.models.signals import post_save

class Reserve(models.Model):
    reserve_id = models.CharField(max_length=100, null=False, blank=False, unique=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    parkings = models.ManyToManyField(Parking, through='ReserveParkings')
    subtotal = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    total = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.parkings} con id:{self.reserve_id}' 
    
    def update_totals(self):
        self.update_subtotal()
        self.update_total()
        """
        # se intenta obtener la orden de la reserva
        order = self.order_set.first()
        # si la orden existe se actualiza su total (por si se modifico)
        if order:
            order.update_total()"""
        if self.order:
            self.order.update_total()
    
    def update_subtotal(self):
          # metodos para obtener obj parking y ReserveParking en la misma consulta
        self.subtotal = sum([cp.quantity * cp.parking.price_hour for cp in self.parkings_related()])                             
        self.save()
    
    def update_total(self):
        FEE = 0.05
        self.total = self.subtotal 
        self.save()

    def parkings_related(self):
        # Mejora el pedido de consulta relacionada a una sola consulta
        return self.reserveparkings_set.select_related('parking')

    @property
    def order(self):
        # order_set es la relacion uno a muchos
        return self.order_set.first()

class ReserveParkingsManager(models.Manager):
    
    def create_or_update_quantity(self, reserve, parking, quantity=1):
        # metodo que permite obtener un objeto, si no existe lo crea
        object, created = self.get_or_create(reserve=reserve, parking=parking)

        if not created:
            quantity = object.quantity + quantity 
            
        object.update_quantity(quantity)
        return object

class ReserveParkings(models.Model):
    reserve = models.ForeignKey(Reserve, on_delete=models.CASCADE)
    parking = models.ForeignKey(Parking, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = ReserveParkingsManager()

    def update_quantity(self, quantity=1):
        self.quantity = quantity 
        self.save()

def set_reserve_id(sender, instance, *args, **kwargs):
    if not instance.reserve_id:
        instance.reserve_id = str(uuid.uuid4())

def update_totals(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clean':
      instance.update_totals()

def post_save_update_totals(sender, instance, *args, **kwargs):
    instance.reserve.update_totals()

        
pre_save.connect(set_reserve_id, sender=Reserve)
# Cuando se cree un objeto ReserveParkings se ejecutra el signal post_save
post_save.connect(post_save_update_totals, sender=ReserveParkings)
# cuando se agregue una reserva, se elimine o se limpie se calculan los totales.
m2m_changed.connect(update_totals, sender=Reserve.parkings.through)

reserves/views.py
from django.shortcuts import render
from .models import Reserve
from .utils import get_or_create_reserve
from parking.models import Parking
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from .models import ReserveParkings
# Create your views here.
def reserve(request):    
    reserve = get_or_create_reserve(request)    
    
    return render(request, 'reserves/reserve.html', {
        'reserve': reserve
    })

def add(request):
    reserve = get_or_create_reserve(request)
    # obtiene el producto del formulario, con su name parking_id declarado en add.html
    parking = Parking.objects.get(pk=request.POST.get('parking_id'))    
    
    quantity = int(request.POST.get('quantity', 1))
    """
    # Se agrega el objeto de reserva a la relacion reserve-parking
    reserve.parkings.add(parking,through_defaults={
        'quantity': quantity
    } )    #reserve.parkings.add(parking)"""
    # 
    reserve_parking = ReserveParkings.objects.create_or_update_quantity(reserve=reserve, parking=parking, quantity=quantity)
   
    return render(request, 'reserves/add.html', {
        'quantity': quantity,
        'parking': parking
    })

def remove(request):
    reserve = get_or_create_reserve(request)
    parking = get_object_or_404(Parking, pk=request.POST.get('parking_id'))    

    reserve.parkings.remove(parking)

    return redirect('reserves:reserve')

reserves/templates/reserves/snippets/add.html
<div class="mt-5">
    <!-- RESERVA HORA -->
    <div class="container text-center my-4">
        <form action="{% url 'reserves:add' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="parking_id" value="{{ parking.id }} ">
            <div class="d-inline-flex border border-primary rounded-pill p-2 align-items-center" name='quantity'
                value="110" style="background-color: white;">
                <div class="px-3 d-flex">
                    <div><button type="button" class="btn btn-primary rounded-circle" id="remove">-</button></div>
                    <input type="number" name="quantity" value="1" class="form-control col-sm-1 text-center text-center"
                        style="width: 50px;" id="quantity" readonly>
                    <div><button type="button" class="btn btn-primary rounded-circle" id="add">+</button></div>

                </div>
                <div class="border-start border-primary mx-2" style="height: 100%;">
                    <div class="px-3">
                        <button type="submit" class="btn btn-transparen d-flex p-2 align-items-center">
                        <div type="submit" p class="mb-0 fw-bold">Reservar Horas</div>
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <!-- RESERVA ESTADIA -->
    <div class="container text-center my-4">
        <form action="{% url 'reserves:add' %}" method="post">
            {% csrf_token %}
            <button class="d-inline-flex border border-primary rounded-pill p-2 align-items-center" type="submit"
                name='quantity' value="110" style="background-color: white;">
                <div class="px-3">
                    <p class="mb-1 text-muted">Precio Semana:</p>
                    <p class="mb-0 fw-bold"> ${{ parking.price_day}}</p>
                </div>
                <input type="hidden" name="parking_id" value="{{ parking.id }} ">
                <div class="border-start border-primary mx-2" style="height: 100%;">
                    <div class="px-3">
                        <p class="mb-0 fw-bold">Reservar Estadia</p>
                    </div>
                </div>
        </form>
    </div>
    <!-- RESERVA SEMANAL -->
    <div class="container text-center my-4">
        <form action="{% url 'reserves:add' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="parking_id" value="{{ parking.id }} ">
            <button class="d-inline-flex border border-primary rounded-pill p-2 align-items-center" type="submit"
                name='quantity' value="110" style="background-color: white;">
                <div class="px-3">
                    <p class="mb-1 text-muted">Precio Semana:</p>
                    <p class="mb-0 fw-bold">${{ parking.price_week}}</p>
                </div>
                <div class="border-start border-primary mx-2" style="height: 100%;">
                    <div class="px-3">
                        <p class="mb-0 fw-bold">Reservar Semanal</p>
                    </div>
                </div>
        </form>
    </div>
    <!-- RESERVA MENSUAL -->
    <div class="container text-center my-4">
        <form action="{% url 'reserves:add' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="parking_id" value="{{ parking.id }} ">
            <button class="d-inline-flex border border-primary rounded-pill p-2 align-items-center" type="submit"
                name='quantity' value="110" style="background-color: white;">
                <div class="px-3">
                    <p class="mb-1 text-muted">Precio Mensual:</p>
                    <p class="mb-0 fw-bold">{{ parking.price_month}}</p>
                </div>
                <div class="border-start border-primary mx-2" style="height: 100%;">
                    <div class="px-3">
                        <p class="mb-0 fw-bold">Reservar Mensual</p>
                    </div>
                </div>
        </form>
    </div>

</div>
<script>
    const add = document.getElementById('add')
    const remove = document.getElementById('remove')
    const quantity = document.getElementById('quantity')

    add.addEventListener('click', function () {
        quantity.value = parseInt(quantity.value) + 1
    })
    remove.addEventListener('click', function () {
        value = parseInt(quantity.value)
        if (value != 1) {
            value = value - 1
        }
        quantity.value = value
    })
</script>

reserves/templates/reserves/snippets/remove.html
<form action="{% url 'reserves:remove' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="parking_id" value="{{ parking.id }} ">
    <button type="submit" class="btn btn-link text-danger"> Eliminar </button>

</form>